### PR TITLE
Updating exercise for off canvas nav

### PR DESCRIPTION
**Pull request by justinachoi**
A lot of people in the workshop are having trouble getting this answer and taking quite a bit of time on this section, I figure we could give this one to them :)

### CODE REVIEW

**Comment by justinachoi** [comment]
@winkerVSbecks Would you happen to know how to fix the CircleCI tests?

**Comment by winkerVSbecks** [comment]
It is complaining about `.translate-center {}` in `exercises/index.css`. Could you try this:

```
/* stylelint-disable */
.translate-center {
}
/* stylelint-enable */
```

**Comment by justinachoi** [comment]
@winkerVSbecks Thanks that worked :)

**Comment by justinachoi** [comment]
@winkerVSbecks could you merge this when you get the chance? We have a workshop this afternoon

**Pull request merged**
